# Generated by Django 5.0.4 on 2024-06-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfferJobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000, verbose_name='Text')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('contacts', models.TextField(max_length=200, verbose_name='Contacts')),
                ('date_add', models.DateTimeField(auto_now=True, verbose_name='Date add')),
                ('status', models.CharField(choices=[('confirmed', '✅ Confirmed'), ('rejected', '❌ Rejected'), ('awaits', '⏳ Awaits')], default='awaits', max_length=20)),
            ],
            options={
                'verbose_name': 'offer job',
                'verbose_name_plural': 'offer jobs',
            },
        ),
    ]
