# Generated by Django 5.0.4 on 2024-06-10 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offerjobmodel',
            name='user_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_job_client_offers', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='offerjobmodel',
            name='user_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_job_student_offers', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
    ]
